# Generated by Django 6.0.3 on 2026-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosanitario',
            name='estado',
            field=models.CharField(choices=[('CON', 'Confirmado'), ('APL', 'Aplazado'), ('CAN', 'Cancelado'), ('REA', 'Realizado')], default='CON', max_length=3),
        ),
    ]
