# Generated by Django 6.0.3 on 2026-05-06 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, help_text='Snapshot del nombre en el momento del evento (RN-2 inmutabilidad).', max_length=150, verbose_name='Nombre del usuario')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('ACCEDER', 'Acceder'), ('ANULAR', 'Anular'), ('CONFIGURAR', 'Configurar')], db_index=True, max_length=20, verbose_name='Acción')),
                ('entidad', models.CharField(db_index=True, help_text='Nombre del modelo: Animal, Potrero, Pesaje, etc.', max_length=100, verbose_name='Entidad afectada')),
                ('entidad_id', models.CharField(blank=True, help_text='PK polimórfica del registro afectado.', max_length=100, verbose_name='ID de la entidad')),
                ('modulo_origen', models.CharField(blank=True, help_text='CU-02, CU-03 … CU-09', max_length=20, verbose_name='Módulo origen')),
                ('resumen', models.TextField(blank=True, help_text='Descripción corta legible por humanos.', verbose_name='Resumen')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, null=True, verbose_name='Valores nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP de origen')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Registros de bitácora',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['user', '-fecha'], name='auditoria_b_user_id_11d816_idx'), models.Index(fields=['entidad', '-fecha'], name='auditoria_b_entidad_17c575_idx'), models.Index(fields=['accion', '-fecha'], name='auditoria_b_accion_916c64_idx')],
            },
        ),
    ]
