# Generated by Django 5.2.8 on 2025-11-10 04:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('arete', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1, null=True)),
                ('etapa', models.CharField(blank=True, choices=[('TER', 'Ternero'), ('DES', 'Destete'), ('LEV', 'Levante/Ceba'), ('NOV', 'Novillo'), ('ADU', 'Adulto')], max_length=3, null=True)),
                ('raza', models.CharField(blank=True, max_length=48, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('BOR', 'Borrador')], default='BOR', max_length=3)),
                ('motivo_baja', models.CharField(blank=True, max_length=64, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('potrero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='animals.potrero')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=64)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=64)),
                ('notas', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(max_length=64)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='animals.animal')),
                ('desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='animals.potrero')),
                ('hacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='animals.potrero')),
            ],
        ),
    ]
