# Generated by Django 6.0.3 on 2026-04-27 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('sanitaria', 'Sanitaria'), ('productiva', 'Productiva'), ('potrero', 'Potrero'), ('inventario', 'Inventario')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida')], default='pendiente', max_length=10)),
                ('id_entidad_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_entidad', models.CharField(blank=True, max_length=20, null=True)),
                ('origen', models.CharField(max_length=50)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('observacion_atencion', models.TextField(blank=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_generacion'],
                'permissions': [('view_alertas', 'Puede ver alertas'), ('atender_alertas', 'Puede atender alertas'), ('configurar_alertas', 'Puede configurar reglas de alertas')],
            },
        ),
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sanitaria', 'Sanitaria'), ('productiva', 'Productiva'), ('potrero', 'Potrero'), ('inventario', 'Inventario')], max_length=20)),
                ('subtipo', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('umbral_valor', models.FloatField()),
                ('umbral_unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
                'ordering': ['tipo', 'subtipo'],
                'unique_together': {('tipo', 'subtipo')},
            },
        ),
    ]
