# Generated by Django 6.0.3 on 2026-04-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0004_move_potrero_to_potreros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COM', 'Compra'), ('VEN', 'Venta'), ('SAC', 'Sacrificio')], max_length=3)),
                ('fecha', models.DateField()),
                ('peso_final_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('origen_destino', models.CharField(max_length=200)),
                ('valor_cop', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('CON', 'Confirmado'), ('ANU', 'Anulado')], default='CON', max_length=3)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='animals.animal')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['tipo'], name='transaccion_tipo_d4c924_idx'), models.Index(fields=['estado'], name='transaccion_estado_50b4d0_idx'), models.Index(fields=['fecha'], name='transaccion_fecha_172334_idx'), models.Index(fields=['animal'], name='transaccion_animal__da3cbe_idx')],
            },
        ),
    ]
